version: "3.8"

services:
  server:
    build: .
    container_name: gfva-server # 容器名
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - gfmysql
      - redis

  gfmysql:
    image: registry.cn-beijing.aliyuncs.com/gva/gfva-mysql:1.0
    container_name: gfva-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为3306
    environment:
      MYSQL_ROOT_PASSWORD: "gdkid,,.." # root管理员用户密码

  redis:
    image: redis:6.0.6
    container_name: gfva-redis # 容器名
    restart: always
    ports:
      - '6379:6379'