# jwt configuration
jwt:
  expires-at: 1 # 3600000000000秒 == 1天 默认设置为1天
  refresh-at: 168 # 3600000000000秒 == 1天 , 24 * 7 = 168 刷新的token设置为一星期
  signing-key: 'SliverHorn'

# redis configuration
redis:
  db: 0
  address: '127.0.0.1:6379'
  password: ''

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# casbin configuration
casbin:
  model-path: './public/rbac_model.conf'

# system configuration
system:
  env: 'public' # Change to 'develop' to skip authentication for development mode
  db-type: 'mysql'
  oss-type: 'local'
  error-to-email: false
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  image-width: 240
  image-height: 80
  captcha-in-redis: false

# local configuration
local:
  path: 'uploads/file'

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 域名地址)
qiniu:
  zone: 'ZoneHuaDong' # 配置请看server/integration/upload/internal/qiniu.go
  bucket: ''
  img-path: ''
  use-https: false
  access-key: ''
  secret-key: ''
  use-cdn-domains: false

# minio configuration
minio:
  id: 'minio'
  Path: 'http://localhost:9000'
  Token: ''
  Bucket: 'public'
  UseSsl: false
  Secret: 'minio'
  Endpoint: 'localhost:9000'

# aliyun configuration
aliyun:
  Path: 'https://xxx.oss-cn-beijing.aliyuncs.com'
  Bucket: ''
  ACLType: ''
  Endpoint: 'https://oss-cn-beijing.aliyuncs.com'
  AccessKeyID: ''
  SecretAccessKey: ''
  StorageClassType: 'Standard' # 配置请看server/integration/upload/internal/aliyun.go
